package com.lk.phr.dao;

import com.lk.phr.model.UserQuotaModel;

public interface UserQuotaDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quota
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quota
     *
     * @mbg.generated
     */
    int insert(UserQuotaModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quota
     *
     * @mbg.generated
     */
    int insertSelective(UserQuotaModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quota
     *
     * @mbg.generated
     */
    UserQuotaModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quota
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserQuotaModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_quota
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserQuotaModel record);
}