package com.lk.phr.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_quota
 */
public class UserQuotaModel {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   medical
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.medical
     *
     * @mbg.generated
     */
    private Boolean medical;

    /**
     * Database Column Remarks:
     *   user_history序列号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.user_history_seq_no
     *
     * @mbg.generated
     */
    private Long userHistorySeqNo;

    /**
     * Database Column Remarks:
     *   user_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   指标Code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.quota_code
     *
     * @mbg.generated
     */
    private String quotaCode;

    /**
     * Database Column Remarks:
     *   指标值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.quota_value
     *
     * @mbg.generated
     */
    private String quotaValue;

    /**
     * Database Column Remarks:
     *   指标最小值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.min_value
     *
     * @mbg.generated
     */
    private Double minValue;

    /**
     * Database Column Remarks:
     *   指标最大值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.max_value
     *
     * @mbg.generated
     */
    private Double maxValue;

    /**
     * Database Column Remarks:
     *   flag
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.flag
     *
     * @mbg.generated
     */
    private Integer flag;

    /**
     * Database Column Remarks:
     *   updated
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     * Database Column Remarks:
     *   created
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * Database Column Remarks:
     *   监测日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.check_date
     *
     * @mbg.generated
     */
    private Date checkDate;

    /**
     * Database Column Remarks:
     *   设备编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.device_sn
     *
     * @mbg.generated
     */
    private String deviceSn;

    /**
     * Database Column Remarks:
     *   设备序列号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.device_no
     *
     * @mbg.generated
     */
    private String deviceNo;

    /**
     * Database Column Remarks:
     *   phr体系内用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.phr_uid
     *
     * @mbg.generated
     */
    private Long phrUid;

    /**
     * Database Column Remarks:
     *   设备品牌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_quota.device_brand
     *
     * @mbg.generated
     */
    private String deviceBrand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.id
     *
     * @return the value of user_quota.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.id
     *
     * @param id the value for user_quota.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.medical
     *
     * @return the value of user_quota.medical
     *
     * @mbg.generated
     */
    public Boolean getMedical() {
        return medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.medical
     *
     * @param medical the value for user_quota.medical
     *
     * @mbg.generated
     */
    public void setMedical(Boolean medical) {
        this.medical = medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.user_history_seq_no
     *
     * @return the value of user_quota.user_history_seq_no
     *
     * @mbg.generated
     */
    public Long getUserHistorySeqNo() {
        return userHistorySeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.user_history_seq_no
     *
     * @param userHistorySeqNo the value for user_quota.user_history_seq_no
     *
     * @mbg.generated
     */
    public void setUserHistorySeqNo(Long userHistorySeqNo) {
        this.userHistorySeqNo = userHistorySeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.user_id
     *
     * @return the value of user_quota.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.user_id
     *
     * @param userId the value for user_quota.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.quota_code
     *
     * @return the value of user_quota.quota_code
     *
     * @mbg.generated
     */
    public String getQuotaCode() {
        return quotaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.quota_code
     *
     * @param quotaCode the value for user_quota.quota_code
     *
     * @mbg.generated
     */
    public void setQuotaCode(String quotaCode) {
        this.quotaCode = quotaCode == null ? null : quotaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.quota_value
     *
     * @return the value of user_quota.quota_value
     *
     * @mbg.generated
     */
    public String getQuotaValue() {
        return quotaValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.quota_value
     *
     * @param quotaValue the value for user_quota.quota_value
     *
     * @mbg.generated
     */
    public void setQuotaValue(String quotaValue) {
        this.quotaValue = quotaValue == null ? null : quotaValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.min_value
     *
     * @return the value of user_quota.min_value
     *
     * @mbg.generated
     */
    public Double getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.min_value
     *
     * @param minValue the value for user_quota.min_value
     *
     * @mbg.generated
     */
    public void setMinValue(Double minValue) {
        this.minValue = minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.max_value
     *
     * @return the value of user_quota.max_value
     *
     * @mbg.generated
     */
    public Double getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.max_value
     *
     * @param maxValue the value for user_quota.max_value
     *
     * @mbg.generated
     */
    public void setMaxValue(Double maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.flag
     *
     * @return the value of user_quota.flag
     *
     * @mbg.generated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.flag
     *
     * @param flag the value for user_quota.flag
     *
     * @mbg.generated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.updated
     *
     * @return the value of user_quota.updated
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.updated
     *
     * @param updated the value for user_quota.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.created
     *
     * @return the value of user_quota.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.created
     *
     * @param created the value for user_quota.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.check_date
     *
     * @return the value of user_quota.check_date
     *
     * @mbg.generated
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.check_date
     *
     * @param checkDate the value for user_quota.check_date
     *
     * @mbg.generated
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.device_sn
     *
     * @return the value of user_quota.device_sn
     *
     * @mbg.generated
     */
    public String getDeviceSn() {
        return deviceSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.device_sn
     *
     * @param deviceSn the value for user_quota.device_sn
     *
     * @mbg.generated
     */
    public void setDeviceSn(String deviceSn) {
        this.deviceSn = deviceSn == null ? null : deviceSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.device_no
     *
     * @return the value of user_quota.device_no
     *
     * @mbg.generated
     */
    public String getDeviceNo() {
        return deviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.device_no
     *
     * @param deviceNo the value for user_quota.device_no
     *
     * @mbg.generated
     */
    public void setDeviceNo(String deviceNo) {
        this.deviceNo = deviceNo == null ? null : deviceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.phr_uid
     *
     * @return the value of user_quota.phr_uid
     *
     * @mbg.generated
     */
    public Long getPhrUid() {
        return phrUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.phr_uid
     *
     * @param phrUid the value for user_quota.phr_uid
     *
     * @mbg.generated
     */
    public void setPhrUid(Long phrUid) {
        this.phrUid = phrUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_quota.device_brand
     *
     * @return the value of user_quota.device_brand
     *
     * @mbg.generated
     */
    public String getDeviceBrand() {
        return deviceBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_quota.device_brand
     *
     * @param deviceBrand the value for user_quota.device_brand
     *
     * @mbg.generated
     */
    public void setDeviceBrand(String deviceBrand) {
        this.deviceBrand = deviceBrand == null ? null : deviceBrand.trim();
    }
}