spring:
  profiles:
    active: dev
  application:
    name: budd

logging:
  file:
    path: /datalog/weblog/${spring.application.name}
  config: classpath:logback-spring.xml

server:
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    connection-timeout: 30000
  servlet:
    context-path: /budd
    session:
      timeout: 60