package com.lk.phr.dao.phr;

import com.lk.phr.model.phr.UserHistoryModel;
import com.lk.phr.model.phr.UserHistoryModelWithBLOBs;

public interface UserHistoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated
     */
    int insert(UserHistoryModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated
     */
    int insertSelective(UserHistoryModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated
     */
    UserHistoryModelWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserHistoryModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(UserHistoryModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserHistoryModel record);
}