/*
 * The MIT License (MIT)
 *
 * Copyright © 2023 xrv <xrv@live.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package io.github.ehlxr;

import com.fasterxml.jackson.core.type.TypeReference;
import io.github.ehlxr.util.JsonUtils;

import java.util.Map;

/**
 * @author ehlxr
 * @since 2023-03-15 16:08.
 */
public class File {
    public static void main(String[] args) {
        String str0 = "{\"mode\":0,\"isIOSAutoPlay\":false,\"isAndroidAutoPlay\":false,\"isShowDefaultPic\":false,\"isShowWeChatCircleShareButton\":false,\"isForceUpdate\":true,\"isGzhFullScreen\":false,\"isGzhAutoPlay\":false,\"isSharePageFullScreen\":false,\"isSharePageAutoPlay\":false,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":false,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":0,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":0,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"csVideoShareH5Title\":\"\",\"activityMoney\":2.88,\"privacyAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoagreement.html\",\"serviceAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoservice.html\",\"h5Domain\":\"https://vlogh5.piaoquantv.com/\",\"sendVideoIgnoreAuthorizeMobile\":1,\"sendVideoPostAuthorizeMobile\":1,\"noGrantLoginEnable\":1}";
        String str2 = "{\"mode\":0,\"isIOSAutoPlay\":false,\"isAndroidAutoPlay\":false,\"isShowDefaultPic\":false,\"isShowWeChatCircleShareButton\":false,\"isForceUpdate\":true,\"isGzhFullScreen\":false,\"isGzhAutoPlay\":false,\"isSharePageFullScreen\":false,\"isSharePageAutoPlay\":false,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":false,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":0,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":0,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"csVideoShareH5Title\":\"\",\"activityMoney\":2.88,\"privacyAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoagreement.html\",\"serviceAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoservice.html\"}";
        String str3 = "{\"mode\":0,\"isIOSAutoPlay\":false,\"isAndroidAutoPlay\":false,\"isShowDefaultPic\":false,\"isShowWeChatCircleShareButton\":false,\"isForceUpdate\":true,\"isGzhFullScreen\":false,\"isGzhAutoPlay\":false,\"isSharePageFullScreen\":false,\"isSharePageAutoPlay\":false,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":false,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":0,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":0,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"csVideoShareH5Title\":\"\",\"activityMoney\":2.88,\"privacyAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoagreement.html\",\"serviceAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoservice.html\"}";
        String str4 = "{\"mode\":0,\"isIOSAutoPlay\":false,\"isAndroidAutoPlay\":false,\"isShowDefaultPic\":false,\"isShowWeChatCircleShareButton\":false,\"isForceUpdate\":true,\"isGzhFullScreen\":false,\"isGzhAutoPlay\":false,\"isSharePageFullScreen\":true,\"isSharePageAutoPlay\":false,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":false,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":0,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":1,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"csVideoShareH5Title\":\"\",\"activityMoney\":2.88,\"privacyAgreementUrl\":\"https://rescdn.piaoquantv.com/agreement/videoagreement.html\",\"serviceAgreementUrl\":\"https://rescdn.piaoquantv.com/agreement/videoservice.html\",\"h5Domain\":\"https://vlogh5.piaoquantv.com/\",\"sendVideoIgnoreAuthorizeMobile\":1,\"sendVideoPostAuthorizeMobile\":1,\"noGrantLoginEnable\":1}";
        String str5 = "{\"mode\":0,\"isIOSAutoPlay\":false,\"isAndroidAutoPlay\":false,\"isShowDefaultPic\":false,\"isShowWeChatCircleShareButton\":false,\"isForceUpdate\":true,\"isGzhFullScreen\":false,\"isGzhAutoPlay\":false,\"isSharePageFullScreen\":false,\"isSharePageAutoPlay\":false,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":false,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":0,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":1,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"privacyAgreementUrl\":\"https://rescdn.piaoquantv.com/agreement/videoagreement.html\",\"serviceAgreementUrl\":\"https://rescdn.piaoquantv.com/agreement/videoservice.html\",\"h5Domain\":\"https://vlogh5.piaoquantv.com/\",\"sendVideoIgnoreAuthorizeMobile\":1,\"sendVideoPostAuthorizeMobile\":1,\"noGrantLoginEnable\":1}";
        String str6 = "{\"mode\":0,\"isIOSAutoPlay\":false,\"isAndroidAutoPlay\":false,\"isShowDefaultPic\":false,\"isShowWeChatCircleShareButton\":false,\"isForceUpdate\":true,\"isGzhFullScreen\":false,\"isGzhAutoPlay\":false,\"isSharePageFullScreen\":false,\"isSharePageAutoPlay\":false,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":false,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":0,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":0,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"csVideoShareH5Title\":\"\",\"activityMoney\":2.88,\"privacyAgreementUrl\":\"https://rescdn.piaoquantv.com/agreement/videoagreement.html\",\"serviceAgreementUrl\":\"https://rescdn.piaoquantv.com/agreement/videoservice.html\",\"h5Domain\":\"https://vlogh5.piaoquantv.com/\",\"sendVideoIgnoreAuthorizeMobile\":1,\"sendVideoPostAuthorizeMobile\":1,\"noGrantLoginEnable\":1}";
        String str7 = "{\"mode\":0,\"isIOSAutoPlay\":false,\"isAndroidAutoPlay\":false,\"isShowDefaultPic\":false,\"isShowWeChatCircleShareButton\":false,\"isForceUpdate\":true,\"isGzhFullScreen\":false,\"isGzhAutoPlay\":false,\"isSharePageFullScreen\":false,\"isSharePageAutoPlay\":false,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":false,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":0,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":0,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"csVideoShareH5Title\":\"\",\"activityMoney\":2.88,\"privacyAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoagreement.html\",\"serviceAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoservice.html\"}";
        String str10 = "{\"mode\":0,\"isIOSAutoPlay\":false,\"isAndroidAutoPlay\":false,\"isShowDefaultPic\":false,\"isShowWeChatCircleShareButton\":false,\"isForceUpdate\":true,\"isGzhFullScreen\":false,\"isGzhAutoPlay\":false,\"isSharePageFullScreen\":false,\"isSharePageAutoPlay\":false,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"shortShareFriendPath\": \"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"addMaskGuide\":true,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":-1,\"addBubbleDuration\":5,\"barrageUiShow\": true,\"barrageSwitchOpen\": true}";
        String str17 = "{\"mode\":0,\"isIOSAutoPlay\":true,\"isAndroidAutoPlay\":true,\"isShowDefaultPic\":true,\"isShowWeChatCircleShareButton\":true,\"isForceUpdate\":true,\"isGzhFullScreen\":true,\"isGzhAutoPlay\":true,\"isSharePageFullScreen\":true,\"isSharePageAutoPlay\":true,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":true,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":1,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":1,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"csVideoShareH5Title\":\"\",\"activityMoney\":2.88,\"privacyAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoagreement.html\",\"serviceAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoservice.html\",\"h5Domain\":\"https://vlogh5.piaoquantv.com/\"}";
        String str18 = "{\"mode\":0,\"isIOSAutoPlay\":true,\"isAndroidAutoPlay\":true,\"isShowDefaultPic\":true,\"isShowWeChatCircleShareButton\":true,\"isForceUpdate\":true,\"isGzhFullScreen\":true,\"isGzhAutoPlay\":true,\"isSharePageFullScreen\":true,\"isSharePageAutoPlay\":true,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":true,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":1,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":1,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"csVideoShareH5Title\":\"\",\"activityMoney\":2.88,\"privacyAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoagreement.html\",\"serviceAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoservice.html\",\"h5Domain\":\"https://vlogh5.piaoquantv.com/\"}";
        String str19 = "{\"mode\":0,\"isIOSAutoPlay\":true,\"isAndroidAutoPlay\":true,\"isShowDefaultPic\":true,\"isShowWeChatCircleShareButton\":true,\"isForceUpdate\":true,\"isGzhFullScreen\":true,\"isGzhAutoPlay\":true,\"isSharePageFullScreen\":true,\"isSharePageAutoPlay\":true,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":true,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":1,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":1,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"csVideoShareH5Title\":\"\",\"activityMoney\":2.88,\"privacyAgreementUrl\":\"https://rescdn.piaoquantv.com/agreement/videoagreement.html\",\"serviceAgreementUrl\":\"https://rescdn.piaoquantv.com/agreement/videoservice.html\",\"h5Domain\":\"https://vlogh5.piaoquantv.com/\",\"sendVideoIgnoreAuthorizeMobile\":1,\"sendVideoPostAuthorizeMobile\":1,\"noGrantLoginEnable\":1}";
        String str21 = "{\"mode\":0,\"isIOSAutoPlay\":false,\"isAndroidAutoPlay\":false,\"isShowDefaultPic\":false,\"isShowWeChatCircleShareButton\":false,\"isForceUpdate\":true,\"isGzhFullScreen\":false,\"isGzhAutoPlay\":false,\"isSharePageFullScreen\":false,\"isSharePageAutoPlay\":false,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":false,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":0,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":0,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"csVideoShareH5Title\":\"\",\"activityMoney\":2.88,\"privacyAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoagreement.html\",\"serviceAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoservice.html\",\"h5Domain\":\"https://vlogh5.piaoquantv.com/\",\"sendVideoIgnoreAuthorizeMobile\":1,\"sendVideoPostAuthorizeMobile\":1,\"noGrantLoginEnable\":1}";
        String str22 = "{\"mode\":0,\"isIOSAutoPlay\":false,\"isAndroidAutoPlay\":false,\"isShowDefaultPic\":false,\"isShowWeChatCircleShareButton\":false,\"isForceUpdate\":true,\"isGzhFullScreen\":false,\"isGzhAutoPlay\":false,\"isSharePageFullScreen\":false,\"isSharePageAutoPlay\":false,\"distDir\":\"dist_1_3_4\",\"distNewDir\":\"dist_1_3_4\",\"videoShareFriendPath\":\"pages/user-videos\",\"videoShareMomentPath\":\"pages/user-videos\",\"userShareFriendPath\":\"pages/mine/mine-info\",\"userShareMomentPath\":\"pages/mine/mine-info\",\"addMaskGuide\":false,\"addMaskDayInterval\":2,\"addMaskMaxCount\":3,\"addMaskDuration\":10,\"addBubbleGuide\":true,\"addBubbleDayInterval\":2,\"addBubbleMaxCount\":3,\"addBubbleDuration\":10,\"shortShareFriendPath\":\"pages/shortvideo/shortvideo\",\"shortShareMomentPath\":\"pages/shortvideo/shortvideo\",\"barrageUiShow\":true,\"barrageSwitchOpen\":true,\"sortType\":2,\"barrageInputStates\":0,\"videoBarrageSwitch\":true,\"isOpenUnUploadReason\":false,\"isOpenUploadReason\":false,\"homeTabUserInfoPanel\":false,\"isShowDialogOnUpdate\":false,\"fundebug\":false,\"barrageSection\":30,\"isUploadPageLoadData\":0,\"showPayTipsMaxCount\":2,\"openFollowRemind\":true,\"dayFollowRemind\":1,\"totalFollowRemind\":3,\"sharePageRoute\":0,\"shouldFixWxRenderBug\":1,\"defaultSearchText\":\"搜索你想看的\",\"isShowDetailPageGuide\":false,\"gzhOtherVideoCount\":4,\"otherVideoCount\":10,\"shareVideoDialogCount\":2,\"videoShare2PageNotFoundPercent\":0,\"categoryRouterPercent\":100,\"fixed707Upload\":1,\"albumAvailable\":1,\"csVideoShareH5Title\":\"\",\"activityMoney\":2.88,\"privacyAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoagreement.html\",\"serviceAgreementUrl\":\"https://weapppiccdn.yishihui.com/resources/agreements/videoservice.html\",\"h5Domain\":\"https://vlogh5.piaoquantv.com/\",\"sendVideoIgnoreAuthorizeMobile\":1,\"sendVideoPostAuthorizeMobile\":1,\"noGrantLoginEnable\":1}";

        Map<String, String> j0 = JsonUtils.string2Obj(str0, new TypeReference<>() {
        });
        Map<String, String> j2 = JsonUtils.string2Obj(str2, new TypeReference<>() {
        });
        Map<String, String> j3 = JsonUtils.string2Obj(str3, new TypeReference<>() {
        });
        Map<String, String> j4 = JsonUtils.string2Obj(str4, new TypeReference<>() {
        });
        Map<String, String> j5 = JsonUtils.string2Obj(str5, new TypeReference<>() {
        });
        Map<String, String> j6 = JsonUtils.string2Obj(str6, new TypeReference<>() {
        });
        Map<String, String> j7 = JsonUtils.string2Obj(str7, new TypeReference<>() {
        });
        Map<String, String> j10 = JsonUtils.string2Obj(str10, new TypeReference<>() {
        });
        Map<String, String> j17 = JsonUtils.string2Obj(str17, new TypeReference<>() {
        });
        Map<String, String> j18 = JsonUtils.string2Obj(str18, new TypeReference<>() {
        });
        Map<String, String> j19 = JsonUtils.string2Obj(str19, new TypeReference<>() {
        });
        Map<String, String> j21 = JsonUtils.string2Obj(str21, new TypeReference<>() {
        });
        Map<String, String> j22 = JsonUtils.string2Obj(str22, new TypeReference<>() {
        });


        for (String key : j0.keySet()) {
            System.out.println(key + "|" + j0.get(key) + "|" + j2.remove(key)
                    + "|" + j3.remove(key)
                    + "|" + j4.remove(key)
                    + "|" + j5.remove(key)
                    + "|" + j6.remove(key)
                    + "|" + j7.remove(key)
                    + "|" + j10.remove(key)
                    + "|" + j17.remove(key)
                    + "|" + j18.remove(key)
                    + "|" + j19.remove(key)
                    + "|" + j21.remove(key)
                    + "|" + j22.remove(key));
        }

        System.out.println("j2: " + j2);
        System.out.println("j3: " + j3);
        System.out.println("j4: " + j4);
        System.out.println("j5: " + j5);
        System.out.println("j6: " + j6);
        System.out.println("j7: " + j7);
        System.out.println("j10: " + j10);
        System.out.println("j17: " + j17);
        System.out.println("j18: " + j18);
        System.out.println("j19: " + j19);
        System.out.println("j21: " + j21);
        System.out.println("j22: " + j22);
    }
}
