package com.lk.phr.model.phr;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_history
 */
public class UserHistoryModelWithBLOBs extends UserHistoryModel {
    /**
     * Database Column Remarks:
     *   面诊图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.face_url
     *
     * @mbg.generated
     */
    private String faceUrl;

    /**
     * Database Column Remarks:
     *   舌诊图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.tongue_url
     *
     * @mbg.generated
     */
    private String tongueUrl;

    /**
     * Database Column Remarks:
     *   舌底图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.base_of_tongue_url
     *
     * @mbg.generated
     */
    private String baseOfTongueUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.obj_json
     *
     * @mbg.generated
     */
    private String objJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.face_url
     *
     * @return the value of user_history.face_url
     *
     * @mbg.generated
     */
    public String getFaceUrl() {
        return faceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.face_url
     *
     * @param faceUrl the value for user_history.face_url
     *
     * @mbg.generated
     */
    public void setFaceUrl(String faceUrl) {
        this.faceUrl = faceUrl == null ? null : faceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.tongue_url
     *
     * @return the value of user_history.tongue_url
     *
     * @mbg.generated
     */
    public String getTongueUrl() {
        return tongueUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.tongue_url
     *
     * @param tongueUrl the value for user_history.tongue_url
     *
     * @mbg.generated
     */
    public void setTongueUrl(String tongueUrl) {
        this.tongueUrl = tongueUrl == null ? null : tongueUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.base_of_tongue_url
     *
     * @return the value of user_history.base_of_tongue_url
     *
     * @mbg.generated
     */
    public String getBaseOfTongueUrl() {
        return baseOfTongueUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.base_of_tongue_url
     *
     * @param baseOfTongueUrl the value for user_history.base_of_tongue_url
     *
     * @mbg.generated
     */
    public void setBaseOfTongueUrl(String baseOfTongueUrl) {
        this.baseOfTongueUrl = baseOfTongueUrl == null ? null : baseOfTongueUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.obj_json
     *
     * @return the value of user_history.obj_json
     *
     * @mbg.generated
     */
    public String getObjJson() {
        return objJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.obj_json
     *
     * @param objJson the value for user_history.obj_json
     *
     * @mbg.generated
     */
    public void setObjJson(String objJson) {
        this.objJson = objJson == null ? null : objJson.trim();
    }
}