package com.lk.phr.model.phr;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_history
 */
public class UserHistoryModel {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户中心用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   用户中心组织ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.org_id
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     * Database Column Remarks:
     *   诊断类型（1中医，2西医，3中西医结合）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.medical
     *
     * @mbg.generated
     */
    private Boolean medical;

    /**
     * Database Column Remarks:
     *   删除标志（0：正常，1：删除）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.flag
     *
     * @mbg.generated
     */
    private Integer flag;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * Database Column Remarks:
     *   来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     * Database Column Remarks:
     *   序列号（唯一索引）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.seq_no
     *
     * @mbg.generated
     */
    private Long seqNo;

    /**
     * Database Column Remarks:
     *   外部流水号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.out_no
     *
     * @mbg.generated
     */
    private String outNo;

    /**
     * Database Column Remarks:
     *   检查类型名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.check_type_name
     *
     * @mbg.generated
     */
    private String checkTypeName;

    /**
     * Database Column Remarks:
     *   检查类型代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.check_type_code
     *
     * @mbg.generated
     */
    private String checkTypeCode;

    /**
     * Database Column Remarks:
     *   体检分值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.score
     *
     * @mbg.generated
     */
    private Double score;

    /**
     * Database Column Remarks:
     *   体检对应评价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.evaluate
     *
     * @mbg.generated
     */
    private String evaluate;

    /**
     * Database Column Remarks:
     *   体检地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.check_addr
     *
     * @mbg.generated
     */
    private String checkAddr;

    /**
     * Database Column Remarks:
     *   体检机构
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.check_organization
     *
     * @mbg.generated
     */
    private String checkOrganization;

    /**
     * Database Column Remarks:
     *   设备编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.device_code
     *
     * @mbg.generated
     */
    private String deviceCode;

    /**
     * Database Column Remarks:
     *   设备唯一序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.device_no
     *
     * @mbg.generated
     */
    private String deviceNo;

    /**
     * Database Column Remarks:
     *   熵值分数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.entropy_score
     *
     * @mbg.generated
     */
    private Double entropyScore;

    /**
     * Database Column Remarks:
     *   phr体系内用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.phr_uid
     *
     * @mbg.generated
     */
    private Long phrUid;

    /**
     * Database Column Remarks:
     *   检查子类型 如问卷类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_history.check_sub_type
     *
     * @mbg.generated
     */
    private String checkSubType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.id
     *
     * @return the value of user_history.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.id
     *
     * @param id the value for user_history.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.user_id
     *
     * @return the value of user_history.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.user_id
     *
     * @param userId the value for user_history.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.org_id
     *
     * @return the value of user_history.org_id
     *
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.org_id
     *
     * @param orgId the value for user_history.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.medical
     *
     * @return the value of user_history.medical
     *
     * @mbg.generated
     */
    public Boolean getMedical() {
        return medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.medical
     *
     * @param medical the value for user_history.medical
     *
     * @mbg.generated
     */
    public void setMedical(Boolean medical) {
        this.medical = medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.flag
     *
     * @return the value of user_history.flag
     *
     * @mbg.generated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.flag
     *
     * @param flag the value for user_history.flag
     *
     * @mbg.generated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.updated
     *
     * @return the value of user_history.updated
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.updated
     *
     * @param updated the value for user_history.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.created
     *
     * @return the value of user_history.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.created
     *
     * @param created the value for user_history.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.source
     *
     * @return the value of user_history.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.source
     *
     * @param source the value for user_history.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.seq_no
     *
     * @return the value of user_history.seq_no
     *
     * @mbg.generated
     */
    public Long getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.seq_no
     *
     * @param seqNo the value for user_history.seq_no
     *
     * @mbg.generated
     */
    public void setSeqNo(Long seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.out_no
     *
     * @return the value of user_history.out_no
     *
     * @mbg.generated
     */
    public String getOutNo() {
        return outNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.out_no
     *
     * @param outNo the value for user_history.out_no
     *
     * @mbg.generated
     */
    public void setOutNo(String outNo) {
        this.outNo = outNo == null ? null : outNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.check_type_name
     *
     * @return the value of user_history.check_type_name
     *
     * @mbg.generated
     */
    public String getCheckTypeName() {
        return checkTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.check_type_name
     *
     * @param checkTypeName the value for user_history.check_type_name
     *
     * @mbg.generated
     */
    public void setCheckTypeName(String checkTypeName) {
        this.checkTypeName = checkTypeName == null ? null : checkTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.check_type_code
     *
     * @return the value of user_history.check_type_code
     *
     * @mbg.generated
     */
    public String getCheckTypeCode() {
        return checkTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.check_type_code
     *
     * @param checkTypeCode the value for user_history.check_type_code
     *
     * @mbg.generated
     */
    public void setCheckTypeCode(String checkTypeCode) {
        this.checkTypeCode = checkTypeCode == null ? null : checkTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.score
     *
     * @return the value of user_history.score
     *
     * @mbg.generated
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.score
     *
     * @param score the value for user_history.score
     *
     * @mbg.generated
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.evaluate
     *
     * @return the value of user_history.evaluate
     *
     * @mbg.generated
     */
    public String getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.evaluate
     *
     * @param evaluate the value for user_history.evaluate
     *
     * @mbg.generated
     */
    public void setEvaluate(String evaluate) {
        this.evaluate = evaluate == null ? null : evaluate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.check_addr
     *
     * @return the value of user_history.check_addr
     *
     * @mbg.generated
     */
    public String getCheckAddr() {
        return checkAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.check_addr
     *
     * @param checkAddr the value for user_history.check_addr
     *
     * @mbg.generated
     */
    public void setCheckAddr(String checkAddr) {
        this.checkAddr = checkAddr == null ? null : checkAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.check_organization
     *
     * @return the value of user_history.check_organization
     *
     * @mbg.generated
     */
    public String getCheckOrganization() {
        return checkOrganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.check_organization
     *
     * @param checkOrganization the value for user_history.check_organization
     *
     * @mbg.generated
     */
    public void setCheckOrganization(String checkOrganization) {
        this.checkOrganization = checkOrganization == null ? null : checkOrganization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.device_code
     *
     * @return the value of user_history.device_code
     *
     * @mbg.generated
     */
    public String getDeviceCode() {
        return deviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.device_code
     *
     * @param deviceCode the value for user_history.device_code
     *
     * @mbg.generated
     */
    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode == null ? null : deviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.device_no
     *
     * @return the value of user_history.device_no
     *
     * @mbg.generated
     */
    public String getDeviceNo() {
        return deviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.device_no
     *
     * @param deviceNo the value for user_history.device_no
     *
     * @mbg.generated
     */
    public void setDeviceNo(String deviceNo) {
        this.deviceNo = deviceNo == null ? null : deviceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.entropy_score
     *
     * @return the value of user_history.entropy_score
     *
     * @mbg.generated
     */
    public Double getEntropyScore() {
        return entropyScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.entropy_score
     *
     * @param entropyScore the value for user_history.entropy_score
     *
     * @mbg.generated
     */
    public void setEntropyScore(Double entropyScore) {
        this.entropyScore = entropyScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.phr_uid
     *
     * @return the value of user_history.phr_uid
     *
     * @mbg.generated
     */
    public Long getPhrUid() {
        return phrUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.phr_uid
     *
     * @param phrUid the value for user_history.phr_uid
     *
     * @mbg.generated
     */
    public void setPhrUid(Long phrUid) {
        this.phrUid = phrUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_history.check_sub_type
     *
     * @return the value of user_history.check_sub_type
     *
     * @mbg.generated
     */
    public String getCheckSubType() {
        return checkSubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_history.check_sub_type
     *
     * @param checkSubType the value for user_history.check_sub_type
     *
     * @mbg.generated
     */
    public void setCheckSubType(String checkSubType) {
        this.checkSubType = checkSubType == null ? null : checkSubType.trim();
    }
}